backend:
  name: git-gateway
  branch: Gatsby-+-Typescript-Integration

media_folder: static/img
public_folder: /img

collections:
  - name: 'ourTeam'
    label: 'ourTeam'
    folder: 'content/ourTeam'
    create: true
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'file' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'services'
    folder: 'content/services'
    create: true
    slug: "services/{{slug}}"
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'file' }
      - { label: 'Short Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }